### ISSUE TITLE
How does Notifications handle resending message?

### ISSUE THREAD

**Issue by Terrox** [uday-kokitkar/extended-learndash-notifications#2]
I see in the code that notifications are only sent once per trigger.

Does notification know when to send again?

This is how I think it works now, which is a problem:
Course expires, email is sent to user.
User re-enrolls in course.
Course expires again, but email is not sent because email was already sent the first time. But it should send, because this is another expiry.
This is relevant for courses which need to be taken again after certificates expire, for qualifications etc.

**Comment by uday-kokitkar** [comment]
@Terrox 
It works as per the LD notifications plugin's logic. If the notification is not being sent after second enrollment, that should be the limitation in the LD notifications plugin. Please reach out to LD support for it.
Thanks.

**Comment by Terrox** [comment]
I was hoping someone else would know, I'm not sure how to get to LD support

**Comment by uday-kokitkar** [comment]
LD support means LearnDash support. Kindly log in to this site and raise a ticket. Thanks.
https://support.learndash.com/
