### ISSUE TITLE
not working with learndash 3.6

### ISSUE THREAD

**Issue by klimrek** [uday-kokitkar/extended-learndash-notifications#3]
i would really like this plugin but im not getting it to work. it will send out an email notification but not to buddy press

**Comment by uday-kokitkar** [comment]
Hi @klimrek 
Thanks for reporting an issue. Which buddyPress version are you using?

**Comment by klimrek** [comment]
The latest version 10 on WordPress 5.9

**Comment by uday-kokitkar** [comment]
Hi @klimrek 
I tested my plugin with
- BuddyPress 10.0
- LearnDash LMS 3.6.0.3
- LearnDash Notification 1.5.3

I see that the users are receiving BuddyPress messages. I guess you don't have the required change in the LearnDash Notification plugin file. Please modify the file as described in the below URL. Let me know if you face any issues. Thanks.
https://github.com/uday-kokitkar/extended-learndash-notifications#important-change-required

**Comment by uday-kokitkar** [comment]
Closing this issue. If you face a problem, please re-open or create a new issue. Thanks.
