### ISSUE TITLE
Not working in our CMS

### ISSUE THREAD

**Issue by sarkarifocus** [uday-kokitkar/extended-learndash-notifications#4]
This plugin is not working in our install. Help me in this plugin i need this feature

**Comment by uday-kokitkar** [comment]
Hi @sarkarifocus 
I tested my plugin with
- BuddyPress 10.0
- LearnDash LMS 3.6.0.3
- LearnDash Notification 1.5.3

I see that the users are receiving BuddyPress messages. I guess you don't have the required change in the LearnDash Notification plugin file. Please modify the file as described in the below URL. Let me know if you face any issues. Thanks.
https://github.com/uday-kokitkar/extended-learndash-notifications#important-change-required

**Comment by uday-kokitkar** [comment]
Closing this issue. If you face a problem, please re-open or create a new issue. Thanks.
