### ISSUE TITLE
Line update in trigger.php

### ISSUE THREAD

**Issue by roly151** [uday-kokitkar/extended-learndash-notifications#5]
Hi, Quick question. I am assuming that the line that needs to be replaced (pasted below) will need to be replaced each time the LD Notifications Addon is updated? 

_IMPORTANT CHANGE REQUIRED

If you are using LearnDash Notification plugin 1.5 or greater, following line must be modified in the LearnDash Notifications plugin to make this extended plugin work.

File: learndash-notifications/src/trigger.php

Line number: 61 (as per the LearnDash Notification v1.5.3)

Original Code at line 61: $is_send = true;

Replace it by $is_send = apply_filters( 'learndash_notifications_send_email', true, $email, $model->post->ID );_

**Comment by uday-kokitkar** [comment]
@roly151 That is correct. Every time you need to replace the line. I have modified the core file code because the LearnDash team don't update the LD Notifications add-on frequently. Only a couple of updates in a year.
